# Here the part of code for connection to get scientific publication
import json
import os
from dotenv import load_dotenv
project_folder = os.path.expanduser('.')  # adjust as appropriate
load_dotenv(os.path.join(project_folder, '.env'))

import requests
# API in order to get information on google Scholar
TOKEN_GOOGLE_SCHOLAR = os.getenv("TOKEN_GOOGLE_SCHOLAR")
ENDPOINT_GOOGLE_SCHOLAR = os.getenv("ENDPOINT_GOOGLE_SCHOLAR")
# KEYWORD = "learning agility"
SEARCH_LANGUAGE = "en"
NUMBER_OF_RESULTS = str(50)
testing_mode = False

class GoogleScholarApi:
    def __init__(self, theme_to_research):
        self.parameters = {
                              "engine": "google_scholar",
                              "q": theme_to_research,
                              "hl": SEARCH_LANGUAGE,
                              "num": NUMBER_OF_RESULTS,
                              "api_key": TOKEN_GOOGLE_SCHOLAR

        }

        self.google_scholar_results_list = []


    # Get res from the api
    def get_google_scholar_results(self):
        if testing_mode:
            self.google_scholar_results = {'search_metadata': {'id': '612699ea216a9d124e09b63d', 'status': 'Success',
                                                               'json_endpoint': 'https://serpapi.com/searches/ca70a035d295dcaa/612699ea216a9d124e09b63d.json',
                                                               'created_at': '2021-08-25 19:28:42 UTC',
                                                               'processed_at': '2021-08-25 19:28:42 UTC',
                                                               'google_scholar_url': 'https://scholar.google.com/scholar?q=learning+agility&hl=en&num=40',
                                                               'raw_html_file': 'https://serpapi.com/searches/ca70a035d295dcaa/612699ea216a9d124e09b63d.html',
                                                               'total_time_taken': 1.82},
                                           'search_parameters': {'engine': 'google_scholar', 'q': 'learning agility',
                                                                 'hl': 'en', 'num': '40'},
                                           'search_information': {'organic_results_state': 'Results for exact spelling',
                                                                  'total_results': 222000, 'time_taken_displayed': 0.06,
                                                                  'query_displayed': 'learning agility'},
                                           'organic_results': [{'position': 0,
                                                                'title': 'Learning agility: A construct whose time has come.',
                                                                'result_id': 'n76zq2FZUGgJ',
                                                                'link': 'https://psycnet.apa.org/record/2010-13314-005',
                                                                'snippet': "A significant consequence of today's dynamic, complex, and uncertain business environments is that leadership skills are subject to continual obsolescence and displacement. To be effective, leaders must demonstrate the flexibility and agility to adapt …",
                                                                'publication_info': {
                                                                    'summary': 'KP De Meuse, G Dai, GS Hallenbeck - … Journal: Practice and …, 2010 - psycnet.apa.org',
                                                                    'authors': [{'name': 'KP De Meuse',
                                                                                 'link': 'https://scholar.google.com/citations?user=YhRRAkwAAAAJ&hl=en&num=20&oi=sra',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=YhRRAkwAAAAJ&engine=google_scholar_author&hl=en',
                                                                                 'author_id': 'YhRRAkwAAAAJ'}]},
                                                                'resources': [
                                                                    {'title': 'bettsolutions.com', 'file_format': 'PDF',
                                                                     'link': 'https://bettsolutions.com/wp-content/uploads/2014/04/Learning_Agility_-_De_Meuse_Dai_Hallenbeck_2010_.pdf'}],
                                                                'inline_links': {
                                                                    'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&q=n76zq2FZUGgJ',
                                                                    'cited_by': {'total': 234,
                                                                                 'link': 'https://scholar.google.com/scholar?cites=7516606054108741279&as_sdt=2005&sciodt=0,5&hl=en&num=20',
                                                                                 'cites_id': '7516606054108741279',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=2005&cites=7516606054108741279&engine=google_scholar&hl=en&num=20'},
                                                                    'related_pages_link': 'https://scholar.google.com/scholar?q=related:n76zq2FZUGgJ:scholar.google.com/&scioq=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                                    'versions': {'total': 12,
                                                                                 'link': 'https://scholar.google.com/scholar?cluster=7516606054108741279&hl=en&num=20&as_sdt=0,5',
                                                                                 'cluster_id': '7516606054108741279',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C5&cluster=7516606054108741279&engine=google_scholar&hl=en&num=20'}}},
                                                               {'position': 1,
                                                                'title': 'Learning agility: In search of conceptual clarity and theoretical grounding',
                                                                'result_id': '8OpN62TWA1YJ',
                                                                'link': 'https://www.cambridge.org/core/journals/industrial-and-organizational-psychology/article/learning-agility-in-search-of-conceptual-clarity-and-theoretical-grounding/3829A626AAD3405C47CCEADE776EE3D6',
                                                                'snippet': "As organizations become more complex and dynamic, individuals' ability to learn from experience becomes more important. Recently, the concept of learning agility has attracted considerable attention from human resource professionals and consultants interested in …",
                                                                'publication_info': {
                                                                    'summary': 'DS DeRue, SJ Ashford, CG Myers - Industrial and Organizational …, 2012 - cambridge.org',
                                                                    'authors': [{'name': 'DS DeRue',
                                                                                 'link': 'https://scholar.google.com/citations?user=mLg59uIAAAAJ&hl=en&num=20&oi=sra',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=mLg59uIAAAAJ&engine=google_scholar_author&hl=en',
                                                                                 'author_id': 'mLg59uIAAAAJ'},
                                                                                {'name': 'SJ Ashford',
                                                                                 'link': 'https://scholar.google.com/citations?user=q_zZulIAAAAJ&hl=en&num=20&oi=sra',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=q_zZulIAAAAJ&engine=google_scholar_author&hl=en',
                                                                                 'author_id': 'q_zZulIAAAAJ'},
                                                                                {'name': 'CG Myers',
                                                                                 'link': 'https://scholar.google.com/citations?user=egFSOjcAAAAJ&hl=en&num=20&oi=sra',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=egFSOjcAAAAJ&engine=google_scholar_author&hl=en',
                                                                                 'author_id': 'egFSOjcAAAAJ'}]},
                                                                'resources': [
                                                                    {'title': 'umich.edu', 'file_format': 'PDF',
                                                                     'link': 'https://deepblue.lib.umich.edu/bitstream/handle/2027.42/92376/j.1754-9434.2012.01444.x.pdf?sequence=1'}],
                                                                'inline_links': {
                                                                    'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&q=8OpN62TWA1YJ',
                                                                    'cited_by': {'total': 239,
                                                                                 'link': 'https://scholar.google.com/scholar?cites=6198033241124760304&as_sdt=2005&sciodt=0,5&hl=en&num=20',
                                                                                 'cites_id': '6198033241124760304',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=2005&cites=6198033241124760304&engine=google_scholar&hl=en&num=20'},
                                                                    'related_pages_link': 'https://scholar.google.com/scholar?q=related:8OpN62TWA1YJ:scholar.google.com/&scioq=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                                    'versions': {'total': 8,
                                                                                 'link': 'https://scholar.google.com/scholar?cluster=6198033241124760304&hl=en&num=20&as_sdt=0,5',
                                                                                 'cluster_id': '6198033241124760304',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C5&cluster=6198033241124760304&engine=google_scholar&hl=en&num=20'}}},
                                                               {'position': 2,
                                                                'title': 'Learning agility as a prime indicator of potential',
                                                                'result_id': 'rxVFKvdadN8J',
                                                                'link': 'https://search.proquest.com/openview/5bd513f5a41c0f56b703dcb3bff358ca/1.pdf?pq-origsite=gscholar&cbl=52465',
                                                                'snippet': 'Selection, staffing, and succession planning should be a combination of looking at those characteristics that do not change much over time and can be detected early (such as intelligence) and those that flower across time as the person learns to deal with fresh …',
                                                                'publication_info': {
                                                                    'summary': 'RW Eichinger, MM Lombardo - People and Strategy, 2004 - search.proquest.com'},
                                                                'inline_links': {
                                                                    'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&q=rxVFKvdadN8J',
                                                                    'cited_by': {'total': 131,
                                                                                 'link': 'https://scholar.google.com/scholar?cites=16101594585368958383&as_sdt=2005&sciodt=0,5&hl=en&num=20',
                                                                                 'cites_id': '16101594585368958383',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=2005&cites=16101594585368958383&engine=google_scholar&hl=en&num=20'},
                                                                    'related_pages_link': 'https://scholar.google.com/scholar?q=related:rxVFKvdadN8J:scholar.google.com/&scioq=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                                    'versions': {'total': 2,
                                                                                 'link': 'https://scholar.google.com/scholar?cluster=16101594585368958383&hl=en&num=20&as_sdt=0,5',
                                                                                 'cluster_id': '16101594585368958383',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C5&cluster=16101594585368958383&engine=google_scholar&hl=en&num=20'}}},
                                                               {'position': 3,
                                                                'title': 'Learning about learning agility',
                                                                'result_id': 'GzFM9tqvKFAJ', 'type': 'Pdf',
                                                                'link': 'https://www.researchgate.net/profile/Adam-Mitchinson/publication/266852352_Learning_About_Learning_Agility/links/543d3e310cf2d6934ebae6ba/Learning-About-Learning-Agility.pdf',
                                                                'snippet': 'In times of change, leaders need to be more agile than ever. Adapting to new business strategies, working across cultures, dealing with temporary virtual teams, and taking on new assignments all demand that leaders be flexible and agile. But what does being “agile” …',
                                                                'publication_info': {
                                                                    'summary': 'A Mitchinson, R Morris - A White Paper, 2012 - researchgate.net',
                                                                    'authors': [{'name': 'R Morris',
                                                                                 'link': 'https://scholar.google.com/citations?user=in6eBIwAAAAJ&hl=en&num=20&oi=sra',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=in6eBIwAAAAJ&engine=google_scholar_author&hl=en',
                                                                                 'author_id': 'in6eBIwAAAAJ'}]},
                                                                'resources': [
                                                                    {'title': 'researchgate.net', 'file_format': 'PDF',
                                                                     'link': 'https://www.researchgate.net/profile/Adam-Mitchinson/publication/266852352_Learning_About_Learning_Agility/links/543d3e310cf2d6934ebae6ba/Learning-About-Learning-Agility.pdf'}],
                                                                'inline_links': {
                                                                    'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&q=GzFM9tqvKFAJ',
                                                                    'cited_by': {'total': 65,
                                                                                 'link': 'https://scholar.google.com/scholar?cites=5776059877072580891&as_sdt=2005&sciodt=0,5&hl=en&num=20',
                                                                                 'cites_id': '5776059877072580891',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=2005&cites=5776059877072580891&engine=google_scholar&hl=en&num=20'},
                                                                    'related_pages_link': 'https://scholar.google.com/scholar?q=related:GzFM9tqvKFAJ:scholar.google.com/&scioq=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                                    'versions': {'total': 4,
                                                                                 'link': 'https://scholar.google.com/scholar?cluster=5776059877072580891&hl=en&num=20&as_sdt=0,5',
                                                                                 'cluster_id': '5776059877072580891',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C5&cluster=5776059877072580891&engine=google_scholar&hl=en&num=20'},
                                                                    'cached_page_link': 'https://scholar.googleusercontent.com/scholar?q=cache:GzFM9tqvKFAJ:scholar.google.com/+learning+agility&hl=en&num=20&as_sdt=0,5'}},
                                                               {'position': 4,
                                                                'title': 'The role of learning agility and career variety in the identification and development of high potential employees',
                                                                'result_id': 'amF7ZFm03kcJ',
                                                                'link': 'https://www.emerald.com/insight/content/doi/10.1108/00483481211212977/full/html',
                                                                'snippet': 'Purpose–A survey study was conducted in seven best practice organizations in the field of talent management. By cross‐checking their existing high potential lists, the authors aimed to examine to which extent assessments of learning agility were able to predict being …',
                                                                'publication_info': {
                                                                    'summary': 'N Dries, T Vantilborgh, R Pepermans - Personnel Review, 2012 - emerald.com',
                                                                    'authors': [{'name': 'N Dries',
                                                                                 'link': 'https://scholar.google.com/citations?user=AZS7EegAAAAJ&hl=en&num=20&oi=sra',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=AZS7EegAAAAJ&engine=google_scholar_author&hl=en',
                                                                                 'author_id': 'AZS7EegAAAAJ'},
                                                                                {'name': 'T Vantilborgh',
                                                                                 'link': 'https://scholar.google.com/citations?user=oVg_O-QAAAAJ&hl=en&num=20&oi=sra',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=oVg_O-QAAAAJ&engine=google_scholar_author&hl=en',
                                                                                 'author_id': 'oVg_O-QAAAAJ'},
                                                                                {'name': 'R Pepermans',
                                                                                 'link': 'https://scholar.google.com/citations?user=b3FzQyIAAAAJ&hl=en&num=20&oi=sra',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=b3FzQyIAAAAJ&engine=google_scholar_author&hl=en',
                                                                                 'author_id': 'b3FzQyIAAAAJ'}]},
                                                                'resources': [
                                                                    {'title': 'kuleuven.be', 'file_format': 'PDF',
                                                                     'link': 'https://lirias.kuleuven.be/retrieve/432658'}],
                                                                'inline_links': {
                                                                    'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&q=amF7ZFm03kcJ',
                                                                    'cited_by': {'total': 179,
                                                                                 'link': 'https://scholar.google.com/scholar?cites=5178774917553545578&as_sdt=2005&sciodt=0,5&hl=en&num=20',
                                                                                 'cites_id': '5178774917553545578',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=2005&cites=5178774917553545578&engine=google_scholar&hl=en&num=20'},
                                                                    'related_pages_link': 'https://scholar.google.com/scholar?q=related:amF7ZFm03kcJ:scholar.google.com/&scioq=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                                    'versions': {'total': 8,
                                                                                 'link': 'https://scholar.google.com/scholar?cluster=5178774917553545578&hl=en&num=20&as_sdt=0,5',
                                                                                 'cluster_id': '5178774917553545578',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C5&cluster=5178774917553545578&engine=google_scholar&hl=en&num=20'}}},
                                                               {'position': 5,
                                                                'title': 'Learning agility: Its evolution as a psychological construct and its empirical relationship to leader success.',
                                                                'result_id': '5Dckrc0h5W4J',
                                                                'link': 'https://psycnet.apa.org/record/2017-52546-002',
                                                                'snippet': 'The concept of learning agility has grown markedly in popularity during the past few years as an approach to assist human-resource professionals and organizational executives with their talent decisions. Nevertheless, there remains much confusion about what is learning …',
                                                                'publication_info': {
                                                                    'summary': 'KP De Meuse - Consulting Psychology Journal: Practice and …, 2017 - psycnet.apa.org',
                                                                    'authors': [{'name': 'KP De Meuse',
                                                                                 'link': 'https://scholar.google.com/citations?user=YhRRAkwAAAAJ&hl=en&num=20&oi=sra',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=YhRRAkwAAAAJ&engine=google_scholar_author&hl=en',
                                                                                 'author_id': 'YhRRAkwAAAAJ'}]},
                                                                'resources': [
                                                                    {'title': 'researchgate.net', 'file_format': 'PDF',
                                                                     'link': 'https://www.researchgate.net/profile/Kenneth-De-Meuse/publication/321438460_Learning_agility_Its_evolution_as_a_psychological_construct_and_its_empirical_relationship_to_leader_success/links/5a3292c10f7e9b2a2833da01/Learning-agility-Its-evolution-as-a-psychological-construct-and-its-empirical-relationship-to-leader-success.pdf'}],
                                                                'inline_links': {
                                                                    'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&q=5Dckrc0h5W4J',
                                                                    'cited_by': {'total': 60,
                                                                                 'link': 'https://scholar.google.com/scholar?cites=7990830281095657444&as_sdt=2005&sciodt=0,5&hl=en&num=20',
                                                                                 'cites_id': '7990830281095657444',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=2005&cites=7990830281095657444&engine=google_scholar&hl=en&num=20'},
                                                                    'related_pages_link': 'https://scholar.google.com/scholar?q=related:5Dckrc0h5W4J:scholar.google.com/&scioq=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                                    'versions': {'total': 7,
                                                                                 'link': 'https://scholar.google.com/scholar?cluster=7990830281095657444&hl=en&num=20&as_sdt=0,5',
                                                                                 'cluster_id': '7990830281095657444',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C5&cluster=7990830281095657444&engine=google_scholar&hl=en&num=20'}}},
                                                               {'position': 6,
                                                                'title': 'A meta-analysis of the relationship between learning agility and leader success',
                                                                'result_id': 'iCWjLUwHKl8J',
                                                                'link': 'https://search.proquest.com/openview/428ec598c55af307b1655affa9c73518/1?pq-origsite=gscholar&cbl=1576346',
                                                                'snippet': 'Although the construct of learning agility is relatively new, its application by human resource professionals to identify and develop talent has been extensive. Corporate testimonials and anecdotal evidence tout repeatedly how important it is to leadership effectiveness. However …',
                                                                'publication_info': {
                                                                    'summary': 'KP De Meuse - Journal of Organizational Psychology, 2019 - search.proquest.com',
                                                                    'authors': [{'name': 'KP De Meuse',
                                                                                 'link': 'https://scholar.google.com/citations?user=YhRRAkwAAAAJ&hl=en&num=20&oi=sra',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=YhRRAkwAAAAJ&engine=google_scholar_author&hl=en',
                                                                                 'author_id': 'YhRRAkwAAAAJ'}]},
                                                                'resources': [{'title': 'hfmtalentindex.co.za',
                                                                               'file_format': 'PDF',
                                                                               'link': 'https://www.hfmtalentindex.co.za/documents/244/Learning_Agility_Meta-Analysis.pdf'}],
                                                                'inline_links': {
                                                                    'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&q=iCWjLUwHKl8J',
                                                                    'cited_by': {'total': 21,
                                                                                 'link': 'https://scholar.google.com/scholar?cites=6857301406389577096&as_sdt=2005&sciodt=0,5&hl=en&num=20',
                                                                                 'cites_id': '6857301406389577096',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=2005&cites=6857301406389577096&engine=google_scholar&hl=en&num=20'},
                                                                    'related_pages_link': 'https://scholar.google.com/scholar?q=related:iCWjLUwHKl8J:scholar.google.com/&scioq=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                                    'versions': {'total': 2,
                                                                                 'link': 'https://scholar.google.com/scholar?cluster=6857301406389577096&hl=en&num=20&as_sdt=0,5',
                                                                                 'cluster_id': '6857301406389577096',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C5&cluster=6857301406389577096&engine=google_scholar&hl=en&num=20'}}},
                                                               {'position': 7,
                                                                'title': 'Leadership development: Exploring, clarifying, and expanding our understanding of learning agility',
                                                                'result_id': 'NmnOT_q2x6sJ',
                                                                'link': 'https://www.cambridge.org/core/journals/industrial-and-organizational-psychology/article/leadership-development-exploring-clarifying-and-expanding-our-understanding-of-learning-agility/0287460FE98A0FD1DB4CBED426D941F9',
                                                                'snippet': 'We read the DeRue, Ashford, and Myers (2012) article with much interest. As a com- pany, Lominger (purchased by Korn/Ferry in 2006) has conducted research on learn- ing agility for nearly 20years. Although much of this research has been internal in the form of technical reports and …',
                                                                'publication_info': {
                                                                    'summary': 'KP De Meuse, G Dai, VV Swisher… - Industrial and …, 2012 - cambridge.org',
                                                                    'authors': [{'name': 'KP De Meuse',
                                                                                 'link': 'https://scholar.google.com/citations?user=YhRRAkwAAAAJ&hl=en&num=20&oi=sra',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=YhRRAkwAAAAJ&engine=google_scholar_author&hl=en',
                                                                                 'author_id': 'YhRRAkwAAAAJ'}]},
                                                                'resources': [
                                                                    {'title': 'researchgate.net', 'file_format': 'PDF',
                                                                     'link': 'https://www.researchgate.net/profile/Kenneth-De-Meuse/publication/263217685_Leadership_Development_Exploring_Clarifying_and_Expanding_Our_Understanding_of_Learning_Agility/links/5a859ac1458515b8af88baaf/Leadership-Development-Exploring-Clarifying-and-Expanding-Our-Understanding-of-Learning-Agility.pdf'}],
                                                                'inline_links': {
                                                                    'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&q=NmnOT_q2x6sJ',
                                                                    'cited_by': {'total': 46,
                                                                                 'link': 'https://scholar.google.com/scholar?cites=12378063287048104246&as_sdt=2005&sciodt=0,5&hl=en&num=20',
                                                                                 'cites_id': '12378063287048104246',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=2005&cites=12378063287048104246&engine=google_scholar&hl=en&num=20'},
                                                                    'related_pages_link': 'https://scholar.google.com/scholar?q=related:NmnOT_q2x6sJ:scholar.google.com/&scioq=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                                    'versions': {'total': 8,
                                                                                 'link': 'https://scholar.google.com/scholar?cluster=12378063287048104246&hl=en&num=20&as_sdt=0,5',
                                                                                 'cluster_id': '12378063287048104246',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C5&cluster=12378063287048104246&engine=google_scholar&hl=en&num=20'}}},
                                                               {'position': 8,
                                                                'title': 'The role of learning agility in executive career success: The results of two field studies',
                                                                'result_id': 'bvdEAtymkFUJ',
                                                                'link': 'https://www.jstor.org/stable/43488163',
                                                                'snippet': 'Although learning agility has been used in many companies as an important consideration for selecting high potential talent, very little scholarly research has been conducted on this construct. This paper presents the results of two field investigations-one cross-sectional and …',
                                                                'publication_info': {
                                                                    'summary': 'G Dai, KP De Meuse, KY Tang - Journal of Managerial Issues, 2013 - JSTOR',
                                                                    'authors': [{'name': 'KP De Meuse',
                                                                                 'link': 'https://scholar.google.com/citations?user=YhRRAkwAAAAJ&hl=en&num=20&oi=sra',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=YhRRAkwAAAAJ&engine=google_scholar_author&hl=en',
                                                                                 'author_id': 'YhRRAkwAAAAJ'}]},
                                                                'resources': [
                                                                    {'title': 'researchgate.net', 'file_format': 'PDF',
                                                                     'link': 'https://www.researchgate.net/profile/Kenneth-De-Meuse/publication/320165264_The_role_of_learning_agility_in_executive_career_success_The_results_of_two_field_studies/links/5a03b37baca272b06ca4c5e7/The-role-of-learning-agility-in-executive-career-success-The-results-of-two-field-studies.pdf'}],
                                                                'inline_links': {
                                                                    'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&q=bvdEAtymkFUJ',
                                                                    'cited_by': {'total': 63,
                                                                                 'link': 'https://scholar.google.com/scholar?cites=6165611353731299182&as_sdt=2005&sciodt=0,5&hl=en&num=20',
                                                                                 'cites_id': '6165611353731299182',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=2005&cites=6165611353731299182&engine=google_scholar&hl=en&num=20'},
                                                                    'related_pages_link': 'https://scholar.google.com/scholar?q=related:bvdEAtymkFUJ:scholar.google.com/&scioq=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                                    'versions': {'total': 6,
                                                                                 'link': 'https://scholar.google.com/scholar?cluster=6165611353731299182&hl=en&num=20&as_sdt=0,5',
                                                                                 'cluster_id': '6165611353731299182',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C5&cluster=6165611353731299182&engine=google_scholar&hl=en&num=20'}}},
                                                               {'position': 9,
                                                                'title': 'The development and validation of a self assessment of learning agility',
                                                                'result_id': 'EycsQqCJ5G4J', 'type': 'Pdf',
                                                                'link': 'http://larryclarkgroup.com/Larry%20Clark%20Group%20-%20viaEdge%20Technical%20Report%20-%20Updated.pdf',
                                                                'snippet': 'The purpose of this technical report is to review the development and validation of a new self assessment of learning agility. The viaEDGE™ instrument was designed to measure Overall Learning Agility, as well as the following five different facets of the construct:(a) Mental …',
                                                                'publication_info': {
                                                                    'summary': 'KP De Meuse, G Dai, RW Eichinger… - Society for Industrial …, 2011 - larryclarkgroup.com',
                                                                    'authors': [{'name': 'KP De Meuse',
                                                                                 'link': 'https://scholar.google.com/citations?user=YhRRAkwAAAAJ&hl=en&num=20&oi=sra',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=YhRRAkwAAAAJ&engine=google_scholar_author&hl=en',
                                                                                 'author_id': 'YhRRAkwAAAAJ'}]},
                                                                'resources': [{'title': 'larryclarkgroup.com',
                                                                               'file_format': 'PDF',
                                                                               'link': 'http://larryclarkgroup.com/Larry%20Clark%20Group%20-%20viaEdge%20Technical%20Report%20-%20Updated.pdf'}],
                                                                'inline_links': {
                                                                    'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&q=EycsQqCJ5G4J',
                                                                    'cited_by': {'total': 36,
                                                                                 'link': 'https://scholar.google.com/scholar?cites=7990662960260065043&as_sdt=2005&sciodt=0,5&hl=en&num=20',
                                                                                 'cites_id': '7990662960260065043',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=2005&cites=7990662960260065043&engine=google_scholar&hl=en&num=20'},
                                                                    'related_pages_link': 'https://scholar.google.com/scholar?q=related:EycsQqCJ5G4J:scholar.google.com/&scioq=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                                    'versions': {'total': 3,
                                                                                 'link': 'https://scholar.google.com/scholar?cluster=7990662960260065043&hl=en&num=20&as_sdt=0,5',
                                                                                 'cluster_id': '7990662960260065043',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C5&cluster=7990662960260065043&engine=google_scholar&hl=en&num=20'},
                                                                    'cached_page_link': 'http://scholar.googleusercontent.com/scholar?q=cache:EycsQqCJ5G4J:scholar.google.com/+learning+agility&hl=en&num=20&as_sdt=0,5'}},
                                                               {'position': 10,
                                                                'title': 'Assessing the construct validity of a measure of learning agility',
                                                                'result_id': 'lC1vDKf2qwYJ',
                                                                'link': 'https://search.proquest.com/openview/f03a08a37640e5dd892680c15924cdeb/1?pq-origsite=gscholar&cbl=18750&diss=y',
                                                                # 'snippet': "This study examined the construct validity of the Choices questionnaire that purported to support the theory of Learning Agility. Specifically, Learning Agility attempts to predict an individual's potential performance in new tasks. The construct validity will be measured by …",
                                                                'publication_info': {
                                                                    'summary': 'JJ Connolly - 2001 - search.proquest.com'},
                                                                'resources': [{'title': 'fiu.edu', 'file_format': 'PDF',
                                                                               'link': 'https://digitalcommons.fiu.edu/cgi/viewcontent.cgi?article=3610&context=etd'}],
                                                                'inline_links': {
                                                                    'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&q=lC1vDKf2qwYJ',
                                                                    'cited_by': {'total': 36,
                                                                                 'link': 'https://scholar.google.com/scholar?cites=480748982573673876&as_sdt=2005&sciodt=0,5&hl=en&num=20',
                                                                                 'cites_id': '480748982573673876',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=2005&cites=480748982573673876&engine=google_scholar&hl=en&num=20'},
                                                                    'related_pages_link': 'https://scholar.google.com/scholar?q=related:lC1vDKf2qwYJ:scholar.google.com/&scioq=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                                    'versions': {'total': 5,
                                                                                 'link': 'https://scholar.google.com/scholar?cluster=480748982573673876&hl=en&num=20&as_sdt=0,5',
                                                                                 'cluster_id': '480748982573673876',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C5&cluster=480748982573673876&engine=google_scholar&hl=en&num=20'}}},
                                                               {'position': 11,
                                                                'title': 'Learning agility: The impact on recruitment and retention',
                                                                'result_id': 'gOKhc0Mc_g4J', 'type': 'Book',
                                                                'link': 'https://books.google.com/books?hl=en&lr=&id=tZgFDAAAQBAJ&oi=fnd&pg=PR5&dq=learning+agility&ots=eIlvYr51Wk&sig=M39KbZH4WbA7BezmhM-lk122kLw',
                                                                'snippet': 'This book concretely defines the concept of learning agility and offers a business case for why organizations of all types should concentrate on building and sustaining this approach. It provides readers with a holistic approach towards the topic, and helps leaders leverage …',
                                                                'publication_info': {
                                                                    'summary': 'LS Gravett, SA Caldwell - 2016 - books.google.com'},
                                                                'inline_links': {
                                                                    'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&q=gOKhc0Mc_g4J',
                                                                    'cited_by': {'total': 28,
                                                                                 'link': 'https://scholar.google.com/scholar?cites=1080332036643873408&as_sdt=2005&sciodt=0,5&hl=en&num=20',
                                                                                 'cites_id': '1080332036643873408',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=2005&cites=1080332036643873408&engine=google_scholar&hl=en&num=20'},
                                                                    'related_pages_link': 'https://scholar.google.com/scholar?q=related:gOKhc0Mc_g4J:scholar.google.com/&scioq=learning+agility&hl=en&num=20&as_sdt=0,5'}},
                                                               {'position': 12,
                                                                'title': 'The role of learning agility in workplace performance and career advancement',
                                                                'result_id': 'bvqpOt6nQ4wJ', 'type': 'Book',
                                                                'link': 'https://search.proquest.com/openview/d61fb423c9c518aa5077eef886dbcbfb/1?pq-origsite=gscholar&cbl=18750',
                                                                'snippet': "The present study sought to examine Learning Agility as a construct. This construct stems from a growing body of literature in the area of adult learning, career development, and industrial and organizational psychology. Learning Agility refers to an individual's ability to …",
                                                                'publication_info': {
                                                                    'summary': 'CL Bedford - 2011 - search.proquest.com'},
                                                                'resources': [{'title': 'umn.edu', 'file_format': 'PDF',
                                                                               'link': 'https://conservancy.umn.edu/bitstream/handle/11299/109995/Bedford_umn_0130E_11770.pdf?seque'}],
                                                                'inline_links': {
                                                                    'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&q=bvqpOt6nQ4wJ',
                                                                    'cited_by': {'total': 40,
                                                                                 'link': 'https://scholar.google.com/scholar?cites=10107106561658321518&as_sdt=2005&sciodt=0,5&hl=en&num=20',
                                                                                 'cites_id': '10107106561658321518',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=2005&cites=10107106561658321518&engine=google_scholar&hl=en&num=20'},
                                                                    'related_pages_link': 'https://scholar.google.com/scholar?q=related:bvqpOt6nQ4wJ:scholar.google.com/&scioq=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                                    'versions': {'total': 4,
                                                                                 'link': 'https://scholar.google.com/scholar?cluster=10107106561658321518&hl=en&num=20&as_sdt=0,5',
                                                                                 'cluster_id': '10107106561658321518',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C5&cluster=10107106561658321518&engine=google_scholar&hl=en&num=20'}}},
                                                               {'position': 13,
                                                                'title': 'Assessing the construct validity of a measure of learning agility.',
                                                                'result_id': 'ULHu0S5-Tr4J',
                                                                'link': 'https://elibrary.ru/item.asp?id=5240618',
                                                                'snippet': "Degree: Ph. D. DegreeYear: 2001 Institute: Florida International University This study examined the construct validity of the Choices questionnaire that purported to support the theory of Learning Agility. Specifically, Learning Agility attempts to predict an individual''s …",
                                                                'publication_info': {
                                                                    'summary': 'JJ Connolly - 2002 - elibrary.ru'},
                                                                'inline_links': {
                                                                    'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&q=ULHu0S5-Tr4J',
                                                                    'cited_by': {'total': 25,
                                                                                 'link': 'https://scholar.google.com/scholar?cites=13713036654945415504&as_sdt=2005&sciodt=0,5&hl=en&num=20',
                                                                                 'cites_id': '13713036654945415504',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=2005&cites=13713036654945415504&engine=google_scholar&hl=en&num=20'},
                                                                    'related_pages_link': 'https://scholar.google.com/scholar?q=related:ULHu0S5-Tr4J:scholar.google.com/&scioq=learning+agility&hl=en&num=20&as_sdt=0,5'}},
                                                               {'position': 14,
                                                                'title': 'Learning agility: Not much is new',
                                                                'result_id': '3PrAQ9CGlEQJ',
                                                                'link': 'https://www.cambridge.org/core/journals/industrial-and-organizational-psychology/article/learning-agility-not-much-is-new/3B034A7D678C14FE4C6148E2E8CE0B41',
                                                                'snippet': 'As pointed out by DeRue, Ashford, and Myers (2012), experience is a funny thing. The same people witnessing the same event may learn wildly different things. Some will learn lessons that positively affect their lives, others will learn nothing, and others may even learn lessons that detract …',
                                                                'publication_info': {
                                                                    'summary': 'S Wang, ME Beier - Industrial and Organizational Psychology, 2012 - cambridge.org',
                                                                    'authors': [{'name': 'ME Beier',
                                                                                 'link': 'https://scholar.google.com/citations?user=h9TnggYAAAAJ&hl=en&num=20&oi=sra',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=h9TnggYAAAAJ&engine=google_scholar_author&hl=en',
                                                                                 'author_id': 'h9TnggYAAAAJ'}]},
                                                                'inline_links': {
                                                                    'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&q=3PrAQ9CGlEQJ',
                                                                    'cited_by': {'total': 18,
                                                                                 'link': 'https://scholar.google.com/scholar?cites=4941722920180316892&as_sdt=2005&sciodt=0,5&hl=en&num=20',
                                                                                 'cites_id': '4941722920180316892',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=2005&cites=4941722920180316892&engine=google_scholar&hl=en&num=20'},
                                                                    'related_pages_link': 'https://scholar.google.com/scholar?q=related:3PrAQ9CGlEQJ:scholar.google.com/&scioq=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                                    'versions': {'total': 6,
                                                                                 'link': 'https://scholar.google.com/scholar?cluster=4941722920180316892&hl=en&num=20&as_sdt=0,5',
                                                                                 'cluster_id': '4941722920180316892',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C5&cluster=4941722920180316892&engine=google_scholar&hl=en&num=20'}}},
                                                               {'position': 15,
                                                                'title': 'Learning agility in clergy: Understanding the personal strategies and situational factors that enable pastors to learn from experience',
                                                                'result_id': '9JinCfonnsUJ',
                                                                'link': 'https://journals.sagepub.com/doi/abs/10.1177/009164710703500302',
                                                                'snippet': 'Relatively little is known about the ongoing development of pastors as leaders. This study focused on learning agility, the combination of personal strategies and situational factors that pastors rely on to capture the lessons their experiences teach them. Interviews with 100 …',
                                                                'publication_info': {
                                                                    'summary': 'RB McKenna, TN Boyd, PR Yost - Journal of Psychology and …, 2007 - journals.sagepub.com',
                                                                    'authors': [{'name': 'RB McKenna',
                                                                                 'link': 'https://scholar.google.com/citations?user=LzHDTOkAAAAJ&hl=en&num=20&oi=sra',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=LzHDTOkAAAAJ&engine=google_scholar_author&hl=en',
                                                                                 'author_id': 'LzHDTOkAAAAJ'}]},
                                                                'inline_links': {
                                                                    'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&q=9JinCfonnsUJ',
                                                                    'cited_by': {'total': 64,
                                                                                 'link': 'https://scholar.google.com/scholar?cites=14239863026649372916&as_sdt=2005&sciodt=0,5&hl=en&num=20',
                                                                                 'cites_id': '14239863026649372916',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=2005&cites=14239863026649372916&engine=google_scholar&hl=en&num=20'},
                                                                    'related_pages_link': 'https://scholar.google.com/scholar?q=related:9JinCfonnsUJ:scholar.google.com/&scioq=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                                    'versions': {'total': 3,
                                                                                 'link': 'https://scholar.google.com/scholar?cluster=14239863026649372916&hl=en&num=20&as_sdt=0,5',
                                                                                 'cluster_id': '14239863026649372916',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C5&cluster=14239863026649372916&engine=google_scholar&hl=en&num=20'}}},
                                                               {'position': 16,
                                                                'title': 'Using learning agility to identify high potentials around the world',
                                                                'result_id': 'M_sR7vi822cJ', 'type': 'Pdf',
                                                                'link': 'http://www.acumen.org.nz/uploads/3/8/1/3/38130931/whitepaperlearning_agility_research_10-10-2008.pdf',
                                                                'snippet': 'An ethnocentric approach refers to a situation where all crucial organizational positions are filled by parent-country nationals from corporate headquarters. A polycentric approach occurs when foreign subsidiaries are staffed primarily by host-country nationals from the …',
                                                                'publication_info': {
                                                                    'summary': 'KP de Meuse, G Dai, GS Hallenbeck, KY Tang - Korn/Ferry Institute, 2008 - acumen.org.nz',
                                                                    'authors': [{'name': 'KP de Meuse',
                                                                                 'link': 'https://scholar.google.com/citations?user=YhRRAkwAAAAJ&hl=en&num=20&oi=sra',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=YhRRAkwAAAAJ&engine=google_scholar_author&hl=en',
                                                                                 'author_id': 'YhRRAkwAAAAJ'}]},
                                                                'resources': [
                                                                    {'title': 'acumen.org.nz', 'file_format': 'PDF',
                                                                     'link': 'http://www.acumen.org.nz/uploads/3/8/1/3/38130931/whitepaperlearning_agility_research_10-10-2008.pdf'}],
                                                                'inline_links': {
                                                                    'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&q=M_sR7vi822cJ',
                                                                    'cited_by': {'total': 28,
                                                                                 'link': 'https://scholar.google.com/scholar?cites=7483782983138278195&as_sdt=2005&sciodt=0,5&hl=en&num=20',
                                                                                 'cites_id': '7483782983138278195',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=2005&cites=7483782983138278195&engine=google_scholar&hl=en&num=20'},
                                                                    'related_pages_link': 'https://scholar.google.com/scholar?q=related:M_sR7vi822cJ:scholar.google.com/&scioq=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                                    'versions': {'total': 11,
                                                                                 'link': 'https://scholar.google.com/scholar?cluster=7483782983138278195&hl=en&num=20&as_sdt=0,5',
                                                                                 'cluster_id': '7483782983138278195',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C5&cluster=7483782983138278195&engine=google_scholar&hl=en&num=20'},
                                                                    'cached_page_link': 'http://scholar.googleusercontent.com/scholar?q=cache:M_sR7vi822cJ:scholar.google.com/+learning+agility&hl=en&num=20&as_sdt=0,5'}},
                                                               {'position': 17,
                                                                'title': 'Conceptualizing learning agility and investigating its nomological network',
                                                                'result_id': 'ZvEI8F6mWXUJ',
                                                                'link': 'https://digitalcommons.fiu.edu/etd/2575/',
                                                                'snippet': 'This dissertation consists of two studies examining the utility and distinctiveness of learning agility in the workplace. The first study examines the nomological networks of two proprietary measures of learning agility in sample of 832 individuals. The learning agility simulation is …',
                                                                'publication_info': {
                                                                    'summary': 'J Allen - 2016 - digitalcommons.fiu.edu'},
                                                                'resources': [{'title': 'fiu.edu', 'file_format': 'PDF',
                                                                               'link': 'https://digitalcommons.fiu.edu/cgi/viewcontent.cgi?article=3780&context=etd'}],
                                                                'inline_links': {
                                                                    'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&q=ZvEI8F6mWXUJ',
                                                                    'cited_by': {'total': 14,
                                                                                 'link': 'https://scholar.google.com/scholar?cites=8455972702049071462&as_sdt=2005&sciodt=0,5&hl=en&num=20',
                                                                                 'cites_id': '8455972702049071462',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=2005&cites=8455972702049071462&engine=google_scholar&hl=en&num=20'},
                                                                    'related_pages_link': 'https://scholar.google.com/scholar?q=related:ZvEI8F6mWXUJ:scholar.google.com/&scioq=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                                    'versions': {'total': 3,
                                                                                 'link': 'https://scholar.google.com/scholar?cluster=8455972702049071462&hl=en&num=20&as_sdt=0,5',
                                                                                 'cluster_id': '8455972702049071462',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C5&cluster=8455972702049071462&engine=google_scholar&hl=en&num=20'},
                                                                    'cached_page_link': 'https://scholar.googleusercontent.com/scholar?q=cache:ZvEI8F6mWXUJ:scholar.google.com/+learning+agility&hl=en&num=20&as_sdt=0,5'}},
                                                               {'position': 18,
                                                                'title': "Developing a Conceptual Integrated Model for the Employee's Learning Agility",
                                                                'result_id': 'M_yE9wn6a_IJ',
                                                                'link': 'https://onlinelibrary.wiley.com/doi/abs/10.1002/piq.21352',
                                                                'snippet': 'The purpose of this study is to develop a conceptual model of learning agility based on an integrated literature review. Learning agility is the ability to learn from experience and apply it when faced with a new and unfamiliar environment. However, the absence of a theoretical …',
                                                                'publication_info': {
                                                                    'summary': 'J Lee, JH Song - Performance Improvement Quarterly, 2020 - Wiley Online Library',
                                                                    'authors': [{'name': 'JH Song',
                                                                                 'link': 'https://scholar.google.com/citations?user=wrbbVIQAAAAJ&hl=en&num=20&oi=sra',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?author_id=wrbbVIQAAAAJ&engine=google_scholar_author&hl=en',
                                                                                 'author_id': 'wrbbVIQAAAAJ'}]},
                                                                'inline_links': {
                                                                    'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&q=M_yE9wn6a_IJ',
                                                                    'cited_by': {'total': 1,
                                                                                 'link': 'https://scholar.google.com/scholar?cites=17468330500400938035&as_sdt=2005&sciodt=0,5&hl=en&num=20',
                                                                                 'cites_id': '17468330500400938035',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=2005&cites=17468330500400938035&engine=google_scholar&hl=en&num=20'},
                                                                    'related_pages_link': 'https://scholar.google.com/scholar?q=related:M_yE9wn6a_IJ:scholar.google.com/&scioq=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                                    'versions': {'total': 2,
                                                                                 'link': 'https://scholar.google.com/scholar?cluster=17468330500400938035&hl=en&num=20&as_sdt=0,5',
                                                                                 'cluster_id': '17468330500400938035',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C5&cluster=17468330500400938035&engine=google_scholar&hl=en&num=20'}}},
                                                               {'position': 19,
                                                                'title': 'Learning agility: The “X” factor in identifying and developing future leaders',
                                                                'result_id': 'n4EPOPmGmGAJ',
                                                                'link': 'https://www.emerald.com/insight/content/doi/10.1108/00197851311320540/full/html',
                                                                'snippet': 'Purpose–Leaders of the future need to be better than the leaders they replace because the challenges are greater, the speed faster, the competition tougher, and the marketplace increasingly global. In short, the leaders of today and tomorrow must be agile leaders. They …',
                                                                'publication_info': {
                                                                    'summary': 'V Swisher - Industrial and Commercial Training, 2013 - emerald.com'},
                                                                'inline_links': {
                                                                    'serpapi_cite_link': 'https://serpapi.com/search.json?engine=google_scholar_cite&q=n4EPOPmGmGAJ',
                                                                    'cited_by': {'total': 20,
                                                                                 'link': 'https://scholar.google.com/scholar?cites=6960461629046620575&as_sdt=2005&sciodt=0,5&hl=en&num=20',
                                                                                 'cites_id': '6960461629046620575',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=2005&cites=6960461629046620575&engine=google_scholar&hl=en&num=20'},
                                                                    'related_pages_link': 'https://scholar.google.com/scholar?q=related:n4EPOPmGmGAJ:scholar.google.com/&scioq=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                                    'versions': {'total': 3,
                                                                                 'link': 'https://scholar.google.com/scholar?cluster=6960461629046620575&hl=en&num=20&as_sdt=0,5',
                                                                                 'cluster_id': '6960461629046620575',
                                                                                 'serpapi_scholar_link': 'https://serpapi.com/search.json?as_sdt=0%2C5&cluster=6960461629046620575&engine=google_scholar&hl=en&num=20'}}}],
                                           'related_searches': [{'query': 'learning agility inventory',
                                                                 'link': 'https://scholar.google.com/scholar?hl=en&num=20&as_sdt=0,5&qsp=1&q=learning+agility+inventory&qst=ib'},
                                                                {'query': 'learning agility ibm',
                                                                 'link': 'https://scholar.google.com/scholar?hl=en&num=20&as_sdt=0,5&qsp=2&q=learning+agility+ibm&qst=ib'},
                                                                {'query': 'burke learning agility',
                                                                 'link': 'https://scholar.google.com/scholar?hl=en&num=20&as_sdt=0,5&qsp=3&q=burke+learning+agility&qst=ib'},
                                                                {'query': 'learning agility competency',
                                                                 'link': 'https://scholar.google.com/scholar?hl=en&num=20&as_sdt=0,5&qsp=4&q=learning+agility+competency&qst=ib'},
                                                                {'query': 'learning agility sustained performance',
                                                                 'link': 'https://scholar.google.com/scholar?hl=en&num=20&as_sdt=0,5&qsp=5&q=learning+agility+sustained+performance&qst=ib'},
                                                                {'query': 'learning agility lominger',
                                                                 'link': 'https://scholar.google.com/scholar?hl=en&num=20&as_sdt=0,5&qsp=6&q=learning+agility+lominger&qst=ib'},
                                                                {'query': 'eichinger learning agility',
                                                                 'link': 'https://scholar.google.com/scholar?hl=en&num=20&as_sdt=0,5&qsp=7&q=eichinger+learning+agility&qst=ib'},
                                                                {'query': 'learning agility assessment aon',
                                                                 'link': 'https://scholar.google.com/scholar?hl=en&num=20&as_sdt=0,5&qsp=8&q=learning+agility+assessment+aon&qst=ib'}],
                                           'pagination': {'current': 1,
                                                          'next': 'https://scholar.google.com/scholar?start=20&q=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                          'other_pages': {
                                                              '2': 'https://scholar.google.com/scholar?start=20&q=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                              '3': 'https://scholar.google.com/scholar?start=40&q=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                              '4': 'https://scholar.google.com/scholar?start=60&q=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                              '5': 'https://scholar.google.com/scholar?start=80&q=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                              '6': 'https://scholar.google.com/scholar?start=100&q=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                              '7': 'https://scholar.google.com/scholar?start=120&q=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                              '8': 'https://scholar.google.com/scholar?start=140&q=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                              '9': 'https://scholar.google.com/scholar?start=160&q=learning+agility&hl=en&num=20&as_sdt=0,5',
                                                              '10': 'https://scholar.google.com/scholar?start=180&q=learning+agility&hl=en&num=20&as_sdt=0,5'}},
                                           'serpapi_pagination': {'current': 1,
                                                                  'next_link': 'https://serpapi.com/search.json?as_sdt=0%2C5&engine=google_scholar&hl=en&num=20&q=learning+agility&start=20',
                                                                  'next': 'https://serpapi.com/search.json?as_sdt=0%2C5&engine=google_scholar&hl=en&num=20&q=learning+agility&start=20',
                                                                  'other_pages': {
                                                                      '2': 'https://serpapi.com/search.json?as_sdt=0%2C5&engine=google_scholar&hl=en&num=20&q=learning+agility&start=20',
                                                                      '3': 'https://serpapi.com/search.json?as_sdt=0%2C5&engine=google_scholar&hl=en&num=20&q=learning+agility&start=40',
                                                                      '4': 'https://serpapi.com/search.json?as_sdt=0%2C5&engine=google_scholar&hl=en&num=20&q=learning+agility&start=60',
                                                                      '5': 'https://serpapi.com/search.json?as_sdt=0%2C5&engine=google_scholar&hl=en&num=20&q=learning+agility&start=80',
                                                                      '6': 'https://serpapi.com/search.json?as_sdt=0%2C5&engine=google_scholar&hl=en&num=20&q=learning+agility&start=100',
                                                                      '7': 'https://serpapi.com/search.json?as_sdt=0%2C5&engine=google_scholar&hl=en&num=20&q=learning+agility&start=120',
                                                                      '8': 'https://serpapi.com/search.json?as_sdt=0%2C5&engine=google_scholar&hl=en&num=20&q=learning+agility&start=140',
                                                                      '9': 'https://serpapi.com/search.json?as_sdt=0%2C5&engine=google_scholar&hl=en&num=20&q=learning+agility&start=160',
                                                                      '10': 'https://serpapi.com/search.json?as_sdt=0%2C5&engine=google_scholar&hl=en&num=20&q=learning+agility&start=180'}}}
            print("""****************************************
Be careful you are on a test branch
****************************************""")
            return self.google_scholar_results
        else:
            google_scholar_results = requests.get(url=ENDPOINT_GOOGLE_SCHOLAR, params=self.parameters)
            google_scholar_results.raise_for_status()
            self.google_scholar_results = google_scholar_results.json()
            return self.google_scholar_results
